apiVersion: v1
kind: Secret
metadata:
  name: fraud-detection-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  LLM_API_KEY: {{ required "A valid .Values.secrets.llmApiKey is required!" .Values.secrets.llmApiKey | quote }}
  OPENAI_API_KEY: {{ required "A valid .Values.secrets.openaiApiKey is required!" .Values.secrets.openaiApiKey | quote }}