apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-detection-config
  namespace: fraud-detection
data:
  QDRANT_HOST: "qdrant"
  QDRANT_PORT: "6333"
  MLFLOW_TRACKING_URI: "http://mlflow:5000"
  ML_API_URL: "http://fraud-ml-api:3000"
  LLM_BASE_URL: "https://api.openai.com/v1"
  LLM_MODEL: "gpt-4o-mini"