apiVersion: v1
kind: Secret
metadata:
  name: mlflow-infra-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  # MLflow currently does not require API keys.
  # Provided for future use.
  LLM_API_KEY: {{ .Values.secrets.llmApiKey | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}